#!/usr/bin/env bash 
#Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
FILENAME="/etc/passwd"
while IFS=: read -r username _ userid _ _ homedir _
do
echo "$username:$userid:$homedir"
done < $FILENAME
